### ISSUE TITLE
Comparing two Ecto DateTimes raises Calendar.ContainsNaiveDateTime not implemented

### ISSUE THREAD

**Issue by bezelga** [lau/calendar#30]
I am trying to compare two datetimes  (based on this [post](http://www.creativedeletion.com/2016/03/07/comparing_dates_in_elixir.html)) and getting the following error:

```
iex(4)> ecto_dt1 = {{2016, 1, 1}, {0, 0, 0}} |> Ecto.DateTime.from_erl
#Ecto.DateTime<2016-01-01T00:00:00Z>
iex(5)> ecto_dt2 = {{2016, 1, 1}, {0, 10, 3}} |> Ecto.DateTime.from_erl
#Ecto.DateTime<2016-01-01T00:10:03Z>
iex(6)>  Calendar.NaiveDateTime.diff(ecto_dt1, ecto_dt2)
** (Protocol.UndefinedError) protocol Calendar.ContainsNaiveDateTime not implemented for #Ecto.DateTime<2016-01-01T00:00:00Z>
    (calendar) lib/calendar/naive_date_time.ex:1: Calendar.ContainsNaiveDateTime.impl_for!/1
    (calendar) lib/calendar/naive_date_time.ex:5: Calendar.ContainsNaiveDateTime.ndt_struct/1
    (calendar) lib/calendar/naive_date_time.ex:325: Calendar.NaiveDateTime.diff/2
(Protocol.UndefinedError) protocol Calendar.ContainsNaiveDateTime not implemented for #Ecto.DateTime
```
- Calendar version is `0.16.0`
- Elixir `1.3.1`

**Comment by lau** [comment]
Did you add [Calecto](https://github.com/lau/calecto) to your dependencies?

**Comment by bezelga** [comment]
@lau it was missing the calector library. thanks
