### ISSUE TITLE
deployment to heroku failed

### ISSUE THREAD

**Issue by ijunaid8989** [lau/calendar#37]
```
== Compilation error on file lib/calendar/naive_date_time/interval.ex ==
** (UndefinedFunctionError) undefined function NaiveDateTime.__struct__/0 (module NaiveDateTime is not available)
    NaiveDateTime.__struct__()
    (elixir) Kernel.Typespec.typespec/3
    (elixir) lib/kernel/typespec.ex:729: anonymous fn/5 in Kernel.Typespec.typespec/3
    (stdlib) lists.erl:1238: :lists.map/2
    (stdlib) lists.erl:1238: :lists.map/2
    (elixir) lib/kernel/typespec.ex:727: Kernel.Typespec.typespec/3
    (elixir) lib/kernel/typespec.ex:383: Kernel.Typespec.translate_type/3
== Compilation error on file lib/calendar/date_time/interval.ex ==
** (UndefinedFunctionError) undefined function DateTime.__struct__/0 (module DateTime is not available)
    DateTime.__struct__()
    (elixir) Kernel.Typespec.typespec/3
    (elixir) lib/kernel/typespec.ex:969: anonymous fn/4 in Kernel.Typespec.fn_args/4
    (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/kernel/typespec.ex:969: Kernel.Typespec.fn_args/4
    (elixir) lib/kernel/typespec.ex:958: Kernel.Typespec.fn_args/5
    (elixir) lib/kernel/typespec.ex:441: Kernel.Typespec.translate_spec/4
== Compilation error on file lib/calendar/time_zone_data.ex ==
** (CompileError) lib/calendar/time_zone_data.ex:107: DateTime.__struct__/0 is undefined, cannot expand struct DateTime
    (elixir) src/elixir_map.erl:58: :elixir_map.translate_struct/4
    (elixir) src/elixir_fn.erl:9: anonymous fn/3 in :elixir_fn.translate/3
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
    (elixir) src/elixir_fn.erl:14: :elixir_fn.translate/3
== Compilation error on file lib/calendar/time.ex ==
** (CompileError) lib/calendar/time.ex:24: Time.__struct__/0 is undefined, cannot expand struct Time
    (elixir) src/elixir_map.erl:58: :elixir_map.translate_struct/4
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
== Compilation error on file lib/calendar/date.ex ==
** (CompileError) lib/calendar/date.ex:34: Date.__struct__/0 is undefined, cannot expand struct Date
    (elixir) src/elixir_map.erl:58: :elixir_map.translate_struct/4
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
== Compilation error on file lib/calendar/date_time/parse.ex ==
** (CompileError) lib/calendar/date_time/parse.ex:178: DateTime.__struct__/0 is undefined, cannot expand struct DateTime
    (elixir) src/elixir_map.erl:58: :elixir_map.translate_struct/4
== Compilation error on file lib/calendar/naive_date_time.ex ==
** (CompileError) lib/calendar/naive_date_time.ex:9: module Calendar.DateTime.Format is not loaded and could not be found
== Compilation error on file lib/calendar/date_time.ex ==
** (CompileError) lib/calendar/date_time.ex:17: module Calendar.Date is not loaded and could not be found
== Compilation error on file lib/calendar/date_time/format.ex ==
** (CompileError) lib/calendar/date_time/format.ex:107: DateTime.__struct__/0 is undefined, cannot expand struct DateTime
    (elixir) src/elixir_map.erl:58: :elixir_map.translate_struct/4
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
```

Am getting this error..

**Comment by lau** [comment]
It sounds like you are using a version of Elixir that is older than 1.3

**Comment by ijunaid8989** [comment]
Yeah I am on `Elixir 1.2.6`.. what would be the compatible version of Calendar for this Elixir version?

**Comment by lau** [comment]
https://github.com/lau/calendar/blob/master/README.md#elixir-versions-earlier-than-13
